/**
 * =============================================================================
 * PDF GENERATOR — Literature review and summary export
 * =============================================================================
 *
 * Uses jsPDF to produce downloadable PDFs: executive summary only, or full
 * report (summary + literature review content + references from sources).
 * Handles markdown-style headings (# ## ###) and page breaks.
 *
 * Usage: await generatePDF({ title, content, sources?, type: 'summary' | 'full_report' })
 */

import jsPDF from 'jspdf';
import type { Source } from '../types';

/** Options for PDF generation */
interface PDFOptions {
    title: string;
    content: string;
    sources?: Source[];
    type: 'summary' | 'full_report';
}

export async function generatePDF(options: PDFOptions): Promise<void> {
    const { title, content, sources, type } = options;

    const doc = new jsPDF();

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxWidth = pageWidth - (2 * margin);

    let yPos = margin;

    // Helper to check page break
    const checkPageBreak = (space: number = 10) => {
        if (yPos + space > pageHeight - margin) {
            doc.addPage();
            yPos = margin;
        }
    };

    // === TITLE PAGE ===
    yPos = pageHeight / 3;

    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text(title, pageWidth / 2, yPos, { align: 'center' });

    yPos += 20;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by Veritas Research Assistant', pageWidth / 2, yPos, { align: 'center' });

    yPos += 10;

    doc.setFontSize(10);
    const dateStr = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });
    doc.text(dateStr, pageWidth / 2, yPos, { align: 'center' });

    // === CONTENT PAGE ===
    doc.addPage();
    yPos = margin;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');

    // Split content into paragraphs and render
    const paragraphs = content.split('\n\n');

    for (const para of paragraphs) {
        if (!para.trim()) continue;

        checkPageBreak(15);

        // Check for markdown headings
        if (para.startsWith('# ')) {
            doc.setFontSize(16);
            doc.setFont('helvetica', 'bold');
            const lines = doc.splitTextToSize(para.substring(2), maxWidth);
            lines.forEach((line: string) => {
                checkPageBreak(8);
                doc.text(line, margin, yPos);
                yPos += 8;
            });
            yPos += 4;
        } else if (para.startsWith('## ')) {
            doc.setFontSize(14);
            doc.setFont('helvetica', 'bold');
            const lines = doc.splitTextToSize(para.substring(3), maxWidth);
            lines.forEach((line: string) => {
                checkPageBreak(7);
                doc.text(line, margin, yPos);
                yPos += 7;
            });
            yPos += 3;
        } else if (para.startsWith('### ')) {
            doc.setFontSize(12);
            doc.setFont('helvetica', 'bold');
            const lines = doc.splitTextToSize(para.substring(4), maxWidth);
            lines.forEach((line: string) => {
                checkPageBreak(6);
                doc.text(line, margin, yPos);
                yPos += 6;
            });
            yPos += 2;
        } else {
            doc.setFontSize(11);
            doc.setFont('helvetica', 'normal');
            const lines = doc.splitTextToSize(para, maxWidth);
            lines.forEach((line: string) => {
                checkPageBreak(5);
                doc.text(line, margin, yPos);
                yPos += 5;
            });
            yPos += 4;
        }
    }

    // === REFERENCES PAGE ===
    if (sources && sources.length > 0) {
        doc.addPage();
        yPos = margin;

        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text('References', margin, yPos);
        yPos += 12;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');

        sources.forEach((source, index) => {
            checkPageBreak(15);

            const refText = `[${index + 1}] ${source.title}`;
            const lines = doc.splitTextToSize(refText, maxWidth);
            lines.forEach((line: string) => {
                doc.text(line, margin, yPos);
                yPos += 5;
            });

            if (source.publisher) {
                doc.setFont('helvetica', 'italic');
                doc.text(`    ${source.publisher}`, margin, yPos);
                doc.setFont('helvetica', 'normal');
                yPos += 5;
            }

            yPos += 3;
        });
    }

    // Save PDF with proper filename
    const filename = type === 'summary'
        ? 'executive_summary.pdf'
        : 'literature_review.pdf';

    doc.save(filename);
}
