/**
 * =============================================================================
 * PDF GENERATOR - ACADEMIC PAPER FORMATTING
 * =============================================================================
 * 
 * Generates professionally formatted PDFs for research reports
 * =============================================================================
 */

import { jsPDF } from 'jspdf';
import type { Source } from '../types';

interface PDFOptions {
    title: string;
    content: string;
    sources?: Source[];
    type: 'summary' | 'full_report';
}

export async function generatePDF(options: PDFOptions): Promise<void> {
    const { title, content, sources, type } = options;

    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 25;
    const maxWidth = pageWidth - (margin * 2);

    let yPosition = margin;

    // Helper to add new page if needed
    const checkPageBreak = (requiredSpace: number = 15) => {
        if (yPosition + requiredSpace > pageHeight - margin) {
            doc.addPage();
            yPosition = margin;
            return true;
        }
        return false;
    };

    // Helper to add text with wrapping
    const addText = (text: string, fontSize: number, isBold: boolean = false, align: 'left' | 'center' = 'left') => {
        doc.setFontSize(fontSize);
        doc.setFont('helvetica', isBold ? 'bold' : 'normal');

        const lines = doc.splitTextToSize(text, maxWidth);

        for (const line of lines) {
            checkPageBreak();
            const xPos = align === 'center' ? pageWidth / 2 : margin;
            doc.text(line, xPos, yPosition, { align });
            yPosition += fontSize * 0.5;
        }
    };

    // === TITLE PAGE ===
    yPosition = pageHeight / 3;

    // Main title
    addText(title, 24, true, 'center');
    yPosition += 15;

    // Subtitle
    addText('Generated by Veritas Research Assistant', 12, false, 'center');
    yPosition += 5;
    addText(new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    }), 10, false, 'center');

    // New page for content
    doc.addPage();
    yPosition = margin;

    // === CONTENT ===
    if (type === 'full_report') {
        // Parse markdown-like content
        const sections = content.split('\n\n');

        for (const section of sections) {
            if (!section.trim()) continue;

            checkPageBreak(20);

            // Check if it's a heading
            if (section.startsWith('# ')) {
                yPosition += 10;
                addText(section.substring(2), 18, true);
                yPosition += 8;
            } else if (section.startsWith('## ')) {
                yPosition += 8;
                addText(section.substring(3), 14, true);
                yPosition += 6;
            } else if (section.startsWith('### ')) {
                yPosition += 6;
                addText(section.substring(4), 12, true);
                yPosition += 4;
            } else {
                // Regular paragraph
                addText(section, 11, false);
                yPosition += 6;
            }
        }
    } else {
        // Summary - single block of text
        addText(content, 11, false);
    }

    // === SOURCES (if provided) ===
    if (sources && sources.length > 0) {
        doc.addPage();
        yPosition = margin;

        addText('References', 16, true);
        yPosition += 10;

        sources.forEach((source, index) => {
            checkPageBreak(15);

            const citation = `[${index + 1}] ${source.title}${source.publisher ? '. ' + source.publisher : ''}${source.date ? ' (' + source.date + ')' : ''}.`;
            addText(citation, 10, false);
            yPosition += 4;
        });
    }

    // Save the PDF
    const filename = type === 'summary'
        ? 'executive_summary.pdf'
        : 'literature_review.pdf';

    doc.save(filename);
}
